// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFWebAPI.Models;

public partial class TEmpresa
{
    public int Id { get; set; }

    public string RazonSocial { get; set; }

    public string Rubro { get; set; }

    public DateTime FechaBaja { get; set; }

    public int CodPostal { get; set; }

    public virtual ICollection<TEnvio> TEnvios { get; set; } = new List<TEnvio>();
}